-
  version: 1.0.{build}
  branches:
    only:
    - master
  configuration:
    - Release
  build:
    project: SanMan_Development.sln
    publish_wap: true
    parallel: true
    verbosity: minimal
  before_build:
  - nuget restore SanMan_Development.sln
  before_package:
  - cmd: 7z a SanMan_Development_Deploy.zip %APPVEYOR_BUILD_FOLDER%\SanMan_Development_Deploy\*
  after_build:
  - cmd: appveyor PushArtifact SanMan_Development_Deploy.zip -DeploymentName SanMan_Development_Deploy
  artifacts:
  - path: SanMan_Development_Deploy.zip
    name: SanMan_Development_Deploy
    type: zip
  deploy:
  - provider: SanMan_Development_Environment
    name: SanMan_Development_Environment
    server: 67.51.178.59
    protocol : http
    site_name: SanMan_Development
    username: CONPAK-TESTWEB1\Administrator
    password:
      secure: SSmx4kANL0vwt/0p5t1wTn9y7rPedcZpDibrVcLm0B8=
    artifact: SanMan_Development_Deploy
    SanMan_Development_Deploy.deploy_website: true
    ntlm: true
    app_offline: true
    on:
      branch: master
      APPVEYOR_REPO_BRANCH: master
